specfile_path: fmf.spec
synced_files:
    - fmf.spec

upstream_project_name: fmf
downstream_package_name: fmf

current_version_command: ["make", "packit-version"]

actions:
  create-archive:
  - make packit-tarball
  - make packit-path

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-rawhide-x86_64
      - fedora-30-x86_64
      - fedora-29-x86_64
