specfile_path: fmf.spec
synced_files:
    - fmf.spec

upstream_package_name: fmf
downstream_package_name: fmf

# Epel9 fails to build because of too old version of setuptools_scm
# Need to create archive with PKG-INFO
actions:
  create-archive:
    - "hatch build -t sdist"
    - "sh -c 'echo dist/fmf-*.tar.gz'"

srpm_build_deps:
  - hatch

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - fedora-all
    - epel-9
    - epel-10

  - job: tests
    trigger: pull_request
    targets:
    - fedora-all
    - epel-9
    - epel-10

  - job: copr_build
    trigger: commit
    branch: main
    targets:
    - fedora-all
    - epel-9
    - epel-10
    list_on_homepage: True
    preserve_project: True
    owner: "@teemtee"
    project: fmf
