specfile_path: fmf.spec
synced_files:
    - fmf.spec

upstream_package_name: fmf
downstream_package_name: fmf

# Epel9 fails to build with dynamic version. Need to create archive with PKG-INFO
# F37 works with setuptools_scm 7.0
actions:
  create-archive:
    - "python3 -m build --sdist --outdir ."
    - "sh -c 'echo fmf-$(hatch version).tar.gz'"
  get-current-version:
    - "hatch version"

srpm_build_deps:
  - python3-build
  - hatch
  - python3-hatch-vcs

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - fedora-all
    - epel-9

  - job: tests
    trigger: pull_request
    targets:
    - fedora-all
    - epel-9

  - job: copr_build
    trigger: commit
    branch: main
    targets:
    - fedora-all
    - epel-9
    list_on_homepage: True
    preserve_project: True
    owner: psss
    project: fmf
