specfile_path: fmf.spec
synced_files:
    - fmf.spec

upstream_project_name: fmf
downstream_package_name: fmf

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-rawhide-x86_64
      - fedora-30-x86_64
      - fedora-29-x86_64

actions:
  post-upstream-clone:
    - export HOME=/tmp
    - pip3 install docutils
    - PATH=$PATH:/tmp/.local/bin
    - make man
    - mv tmp/fmf* .
