name: CI

on:
  workflow_dispatch:
    inputs:
      upload-wheel:
        type: boolean
        required: false
        default: false
        description: Upload wheel as an artifact
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/step_test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-wheel:
    uses: ./.github/workflows/step_build-wheel.yml
    needs: [ tests ]
    with:
      upload: ${{ inputs.upload-wheel || false }}
